-- models/staging/stg_admin_form.sql

{{ config(materialized = 'view')}}

WITH source AS (
        SELECT *
        FROM {{ source('ciyj_raw', 'administrative_form') }}
)

SELECT
        PBSADMINISTRATIVEFORMID AS administrative_form_id,
        VERSIONNUMBER AS version_number,
        COLLECTIONPERIOD AS collection_period,
        RESPONDENTID AS respondent_id,
        CREATED AS created,
        PERIODBEGIN AS period_begin,
        PERIODEND AS period_end,
        FACILITYURBANRURAL AS facility_urban_rural,
        FACILITYFIELDAVERAGENAME AS facility_field_average_name,
        FACILITYREGION AS facility_region,
        YOUTHPOPULATION AS youth_population,
        ATTORNEYVISITS AS attorney_visits,
        FACILITYEVENTSOPENTOSUPPORTIVEPEOPLE AS facility_events_open_to_supportive_people,
        FACILITYDESIGNCAPACITY AS facility_design_capacity,
        GRIEVANCEREPORTSFILEDBYYOUTHS AS grievance_reports_filed_by_youths,
        HASLIAISONFORFAMILIESTOADMINISTRATION AS has_liaison_for_families_to_administration,
        NEWSTAFFINLASTSIXMONTHS AS new_staff_in_last_six_months,
        STAFFTHATLEFTINTHELASTSIXMONTHS AS staff_that_left_in_last_six_months,
        COMMUNITYVOLUNTEERS AS community_volunteers,
        MEMBERSONTHECOUNCIL AS members_on_the_council,
        PROGRAMSUSINGCOMMUNITYVOLUNTEERS AS programs_using_community_volunteers,
        GRIEVANCEREPORTSFILEDBYSTAFF AS grievance_reports_filed_by_staff,
        HOWMANYMEETINGS AS how_many_meetings,
        CONFIRMEDCASESOFABUSEOFYOUTHSBYSTAFFINLASTSIXMONTHS AS confirmed_cases_of_abuse_of_youths_by_staff_in_last_six_months,
        FAMILYINCLUDEDDURINGPOLICYREVIEWS AS family_included_during_policy_reviews,
        TOTALNUMBEROFPROGRAMS AS total_number_of_programs,
        ALLEGEDCASESOFABUSEOFYOUTHSBYSTAFFINLASTSIXMONTHS AS alleged_cases_of_abuse_of_youths_by_staff_in_last_six_months,
        VISITSRECEIVED AS visits_received,
        STAFFSANCTIONEDSTUNGUNS AS staff_sanctioned_stun_guns,
        ALLEDGEDCASESINVOLVINGINAPPROPRIATESEXUALBEHAVIOR AS alleged_cases_involving_inappropriate_sexual_behavior,
        STAFFSANCTIONRELATEDTOYOUTHINLASTSIXMONTHS AS staff_sanction_related_to_youth_in_last_six_months,
        AVERAGEPOSSIBLEVISITATIONHOURSPERWEEK AS average_possible_visitation_hours_per_week,
        ACHIEVABLELEVELS AS achievable_levels,
        CONFIRMEDCASESINVOLVINGINAPPROPRIATESEXUALBEHAVIOR AS confirmed_cases_involving_inappropriate_sexual_behavior,
        YOUTHSRELEASEDPREVPERIOD AS youths_released_prev_period,
        LATERALTRANSFERS AS lateral_transfers,
        YOUTHSRELEASEDCURRENTPERIOD AS youths_released_current_period,
        YOUTHSRELEASEDMONTHPRIOR AS youths_released_month_prior,
        AVERAGELENGTHSTAY AS average_length_stay,
        IDLEWAKINGHOURS AS idle_waking_hours,
        GENDEROFFACILITYPOPULATION AS gender_of_facility_population,
        SCHEDULEDSHIFTCHANGETIME AS scheduled_shift_change_time,
        BUDGETEDCAPACITY AS budgeted_capacity,
        WHITENONHISPANICFEMALESTAFF AS white_non_hispanic_female_staff,
        WHITENONHISPANICMALESTAFF AS white_non_hispanic_male_staff,
        WHITENONHISPANICFEMALEYOUTH AS white_non_hispanic_female_youth,
        WHITENONHISPANICMALEYOUTH AS white_non_hispanic_male_youth,
        OTHERETHNICITYFEMALESTAFF AS other_ethnicity_female_staff,
        OTHERETHNICITYMALESTAFF AS other_ethnicity_male_staff,
        OTHERETHNICITYFEMALEYOUTH AS other_ethnicity_female_youth,
        OTHERETHNICITYMALEYOUTH AS other_ethnicity_male_youth,
        OTHERHISPANICFEMALESTAFF AS other_hispanic_female_staff,
        OTHERHISPANICMALESTAFF AS other_hispanic_male_staff,
        OTHERHISPANICFEMALEYOUTH AS other_hispanic_female_youth,
        OTHERHISPANICMALEYOUTH AS other_hispanic_male_youth,
        BLACKHISPANICFEMALESTAFF AS black_hispanic_female_staff,
        BLACKHISPANICMALESTAFF AS black_hispanic_male_staff,
        BLACKHISPANICFEMALEYOUTH AS black_hispanic_female_youth,
        BLACKHISPANICMALEYOUTH AS black_hispanic_male_youth,
        YOUTHLOCATIONDURINGSHIFTCHANGE AS youth_location_during_shift_change,
        YOUTHACTIVITYDURNINGSHIFTCHANGE AS youth_activity_during_shift_change,
        SHIFTCHANGEDURATION AS shift_change_duration,
        ASIANFEMALESTAFF AS asian_female_staff,
        ASIANMALESTAFF AS asian_male_staff,
        ASIANFEMALEYOUTH AS asian_female_youth,
        ASIANMALEYOUTH AS asian_male_youth,
        PACIFICISLANDERFEMALESTAFF AS pacific_islander_female_staff,
        PACIFICISLANDERMALESTAFF AS pacific_islander_male_staff,
        PACIFICISLANDERFEMALEYOUTH AS pacific_islander_female_youth,
        PACIFICISLANDERMALEYOUTH AS pacific_islander_male_youth,
        SHIFTCHANGEMEETINGSONWEEKDAYS AS shift_change_meetings_on_weekdays,
        SHIFTCHANGEMEETINGSONWEEKENDS AS shift_change_meetings_on_weekends,
        WHITEHISPANICFEMALESTAFF AS white_hispanic_female_staff,
        WHITEHISPANICMALESTAFF AS white_hispanic_male_staff,
        WHITEHISPANICFEMALEYOUTH AS white_hispanic_female_youth,
        WHITEHISPANICMALEYOUTH AS white_hispanic_male_youth,
        AMERICANINDIANFEMALESTAFF AS american_indian_female_staff,
        AMERICANINDIANMALESTAFF AS american_indian_male_staff,
        AMERICANINDIANFEMALEYOUTH AS american_indian_female_youth,
        AMERICANINDIANMALEYOUTH AS american_indian_male_youth,
        BLACKNONHISPANICFEMALESTAFF AS black_non_hispanic_female_staff,
        BLACKNONHISPANICMALESTAFF AS black_non_hispanic_male_staff,
        BLACKNONHISPANICFEMALEYOUTH AS black_non_hispanic_female_youth,
        BLACKNONHISPANICMALEYOUTH AS black_non_hispanic_male_youth
FROM source
